### ISSUE TITLE
Error on callback with MobilePay 

### ISSUE THREAD

**Issue by wexo-team** [QuickPay/magento-v2#11]
When using MobilePay, for some reason everything related to the customer and adresses on the order is per default overridden. This should not be default behaviour in my opinion as it will have the ability to remove important shipping related information that the customer filled in the checkout (e.g. droppoint address etc.)

Also, there are no checks for existence of the addresses, so callbacks can easily fail with the following:
"Uncaught exception 'Error' with message 'Call to a member function addData() on null' in /var/app/current/vendor/quickpay/magento2/Helper/Order.php:222"

**Comment by CodemakersDK** [comment]
It has now been updated, so that if billing or shipping address is filled in checkout it will be saved instead of default DNK values.
