### ISSUE TITLE
main.CRITICAL: Warning: Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by julianchristmas** [QuickPay/magento-v2#14]
On Magento 2.3.x the following error is thrown when customers are passed onto Quickpay for payment: 

`main.CRITICAL: Warning: Cannot modify header information - headers already sent`

The issue seems to be caused by the statement `echo 'OK' ` in the M2.3 specific callback controller: 

https://github.com/QuickPay/magento-v2/blob/238f8d11d145752fbef336c34d420fe90a9dd5d7/Controller/Payment/CallbackM23.php#L258

**Comment by CodemakersDK** [comment]
Updated with _$this->getResponse()->setBody("OK");_
