### ISSUE TITLE
QuickPay: Error.

### ISSUE THREAD

**Issue by WebKenth** [QuickPay/magento-v2#23]
Why...? 

> Model/Adapter/QuickPayAdapter.php

``` 
401: throw new \Magento\Framework\Exception\LocalizedException(__('QuickPay: Error.'));
436: throw new \Magento\Framework\Exception\LocalizedException(__('QuickPay: Error.'));
474: throw new \Magento\Framework\Exception\LocalizedException(__('QuickPay: Error.'));
``` 

Why is this acceptable in the production environment?

No explanations, no reason to stop the entire flow.

If you create an order and wish to capture it, instead of informing the user, you just throw a "QuickPay: Error." if you don't want your module to process it?

This used to be handled gracefully where quickpay would log the incident and let the developers know that there is an issue with the payment, instead it just stops the entire process even if quickpay is not part of the issue. 

In this case if you create an order from backend without filling out the paymentlink you cannot capture the order. This is a perfectly valid behaviour but for god sake let the user know why you can't capture the order instead of throwing the most generic error you possibly could

**Comment by WebKenth** [comment]
But hey, atleast it's translatable ...

**Comment by CodemakersDK** [comment]
It is now being handled appropriately since v 2.1.3
