### ISSUE TITLE
Use "getPriceInclTax" instead of "getBasePriceInclTax" to respect scope config

### ISSUE THREAD

**Issue by JohnNDK** [QuickPay/magento-v2#24]
https://github.com/QuickPay/magento-v2/blob/bdf8c28bef08dd5fbaddc83a03e3faf66b8f2e3d/Model/Adapter/QuickPayAdapter.php#L194

We previously corrected this manually, but latest update removed it. We assumed it would be fixed after talking to support, but apparently it didn't.

Using base price causes issues with multi currency installations, especially with Klarna since it sends base currency values instead of store currency values.

**Comment by CodemakersDK** [comment]
It is now fixed since v 2.1.3.

**Comment by JohnNDK** [comment]
2.1.3 release doesn't match master repository.
The fix is in master, not in the release package.
