### ISSUE TITLE
Undefined array "errorCodes"

### ISSUE THREAD

**Issue by JohnNDK** [QuickPay/magento-v2#25]
https://github.com/QuickPay/magento-v2/blob/bdf8c28bef08dd5fbaddc83a03e3faf66b8f2e3d/Model/Adapter/QuickPayAdapter.php#L397

Class references an undefined errorCodes array, which is causing issues on API call errors.

**Comment by CodemakersDK** [comment]
It has now been fixed as of v 2.1.3, where errorCodes are now defined.
