### ISSUE TITLE
Checkout broken when clicked on "Cancel Payment" on Quickpay

### ISSUE THREAD

**Issue by sathyavempati** [QuickPay/magento-v2#28]
Checkout is broken with message - "Current customer does not have an active cart."

Steps to reproduce:

- Start guest checkout with new email address
- Enter billing and shipping address
- Check "Create Account" checkbox
- Finish the remaining checkout options
- Click on "Place Order" button
- Navigated to QuickPay payment page
- Click on "Cancel Payment" button
- Navigated back to checkout page
- Cannot finish the checkout and keep getting message - "Current customer does not have an active cart."

**Comment by ssandgren** [comment]
@sathyavempati You are using a non-standard/build-in feature to create an account during checkout?

If you use Magento 2 standard Create account, then it works perfectly.
