### ISSUE TITLE
Partial invoice/capture error

### ISSUE THREAD

**Issue by nwyke** [QuickPay/magento-v2#29]
When invoicing only some products, invoice creation fails with the error "QuickPay Validation error: amount - is too large", but amount is captured in Quickpay.
Only way to make a partial invoice, is to select "Capture offline".

**Comment by CodemakersDK** [comment]
@nwyke I suggest that you update your Magento together with QuickPay's module. The case you have mentioned above couldn't have been replicated in our test environment with latest Magento and QuickPay versions.
