### ISSUE TITLE
Authorization amount not added to sales_order_payment

### ISSUE THREAD

**Issue by wexo-team** [QuickPay/magento-v2#7]
In the previous release of this module (the one from Rbech) order transactions (aka sales_order_payment) would have a "base_amount_authorized" set (quite possibly through \Magento\Sales\Model\Order\Payment\Operations\AuthorizeOperation::authorize).

With the new module (this one, QuickPay/magento-v2), the authorized amount is only added as a order comment and not reflected on the sales_order_payment.

**Comment by CodemakersDK** [comment]
It has now been updated, so that order transactions would be reflected on the sales_order_payment.
