### ISSUE TITLE
QuickPay order not showing in Sales > Transaction

### ISSUE THREAD

**Issue by ravimule** [QuickPay/magento-v2#8]
QuickPay order not showing in **Sales > Transaction** on any type of transaction.
Eg: I have placed some orders with test credit cards provided by QuickPay but no order are visible in **Sales > Transaction** menu of Magento2.3.5.
![screenshot-unilever-denmark local-2020 09 10-15_25_16](https://user-images.githubusercontent.com/16305180/92714500-eb26c380-f379-11ea-8a93-9756f7469f22.png)

**Comment by ssandgren** [comment]
@ravimule please send a mail to support@quickpay.net, then we will help you from there

**Comment by CodemakersDK** [comment]
Closed.
